# setwd("~/git/frabento")
devtools::load_all("~/git/frabento")
# library(frabento)

test_that("when input vector is character vector", {
    expect_equal(repl2blank(letters[1:3]),                                            c("a", "", "c"))
    expect_equal(repl2blank(letters[1:3], nskip = 2),                                 c("a", "", ""))
    expect_equal(repl2blank(letters[1:3], first = TRUE),                              c("", "", "c"))
    expect_equal(repl2blank(letters[1:3], last  = TRUE),                              c("a", "", ""))
    expect_equal(repl2blank(letters[1:3], first = TRUE, last  = TRUE),                c("", "", ""))
    expect_equal(repl2blank(letters[1:3], inverse = TRUE),                            c("", "b", ""))
    expect_equal(repl2blank(letters[1:3], inverse = TRUE, first = TRUE),              c("a", "b", ""))
    expect_equal(repl2blank(letters[1:3], inverse = TRUE, last = TRUE),               c("", "b", "c"))
    expect_equal(repl2blank(letters[1:3], inverse = TRUE, first = TRUE, last = TRUE), c("a", "b", "c"))

    expect_equal(repl2blank(letters[1:4]),                                            c("a", "", "c", ""))
    expect_equal(repl2blank(letters[1:4], nskip = 2),                                 c("a", "", "", "d"))
    expect_equal(repl2blank(letters[1:4], first = TRUE),                              c("", "", "c", ""))
    expect_equal(repl2blank(letters[1:4], last  = TRUE),                              c("a", "", "c", ""))
    expect_equal(repl2blank(letters[1:4], first = TRUE, last  = TRUE),                c("", "", "c", ""))
    expect_equal(repl2blank(letters[1:4], inverse = TRUE),                            c("", "b", "", "d"))
    expect_equal(repl2blank(letters[1:4], inverse = TRUE, first = TRUE),              c("a", "b", "", "d"))
    expect_equal(repl2blank(letters[1:4], inverse = TRUE, last = TRUE),               c("", "b", "", "d"))
    expect_equal(repl2blank(letters[1:4], inverse = TRUE, first = TRUE, last = TRUE), c("a", "b", "", "d"))
})
